import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import vm from 'node:vm';
import {appsScript} from '../static/sheets-script.js';
import {sheetSettings} from '../website/google-sheets.mjs';
const id='practice_sheet_id_1234567890',settings={origin:'https://assessment.test',token:'a'.repeat(64),spreadsheet_id:id,tab_name:'Leads'};
const source=appsScript(settings,readFileSync(new URL('../static/import-data.js',import.meta.url),'utf8'));
function fixture(){
 let grid=[['Name','Email','Company'],['Practice Person','p@example.invalid','Acme'],['Incomplete','','Acme']],requests=[],fail=false;const props={},triggers=[];
 const tab={getLastRow:()=>grid.length,getLastColumn:()=>grid[0]?.length||0,getRange:(row=1,col=1,height=1,width=1)=>({getDisplayValues:()=>Array.from({length:height},(_,i)=>Array.from({length:width},(_,j)=>grid[row-1+i]?.[col-1+j]||'')),setValues:values=>{values.forEach((line,i)=>line.forEach((v,j)=>{grid[row-1+i]||=[];grid[row-1+i][col-1+j]=v}))},setValue:value=>{grid[row-1]||=[];grid[row-1][col-1]=value}}),setFrozenRows:()=>{}};
 const book={getId:()=>id,getSheetByName:name=>name==='Leads'?tab:null};
 const ctx={SpreadsheetApp:{getActiveSpreadsheet:()=>book},PropertiesService:{getScriptProperties:()=>({getProperty:k=>props[k],setProperty:(k,v)=>props[k]=v,getProperties:()=>({...props}),setProperties:o=>Object.assign(props,o),deleteProperty:k=>delete props[k]})},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock:()=>{}})},ScriptApp:{getProjectTriggers:()=>[],deleteTrigger:()=>{},newTrigger:handler=>{const t={handler,forSpreadsheet:()=>t,onEdit:()=>t,onFormSubmit:()=>t,timeBased:()=>t,everyMinutes:n=>{t.minutes=n;return t},create:()=>triggers.push(t)};return t}},Utilities:{DigestAlgorithm:{SHA_256:'SHA_256'},computeDigest:(_,s)=>s,base64EncodeWebSafe:s=>Buffer.from(s).toString('base64')},UrlFetchApp:{fetch:(url,o)=>{requests.push({url,body:JSON.parse(o.payload)});return {getResponseCode:()=>fail?503:200,getContentText:()=>JSON.stringify(fail?{error:'Temporary failure'}:url.endsWith('/process')?{processed:false}:{inserted:1,duplicates:0})}}}};
 vm.createContext(ctx);vm.runInContext(source,ctx);return {ctx,props,triggers,requests,grid:()=>grid,setGrid:v=>grid=v,setFail:v=>fail=v};
}
test('script installs edit, form and five-minute triggers and sends complete rows once',()=>{const f=fixture();f.ctx.installInboundDesk();assert.equal(f.triggers.length,3);assert.ok(f.triggers.some(t=>t.minutes===5));assert.equal(f.requests[0].body.rows.length,1);f.ctx.inboundDeskSync();assert.equal(f.requests.filter(r=>r.url.endsWith('/ingest')&&r.body.rows.length).length,1);f.setGrid([['Name','Email','Company'],['Practice Person','p@example.invalid','Acme'],['New Person','n@example.invalid','Acme']]);f.ctx.inboundDeskSync();assert.equal(f.requests.filter(r=>r.url.endsWith('/ingest')&&r.body.rows.length).length,2);});
test('failed delivery is not marked sent and is retried',()=>{const f=fixture();f.setFail(true);assert.throws(()=>f.ctx.installInboundDesk(),/Temporary failure/);assert.equal(Object.keys(f.props).filter(k=>k.startsWith('inbound_sent_')).length,0);f.setFail(false);f.ctx.inboundDeskSync();assert.equal(Object.keys(f.props).filter(k=>k.startsWith('inbound_sent_')).length,1);});
test('a blank tab gets headers without overwriting existing data',()=>{const f=fixture();f.setGrid([]);f.ctx.installInboundDesk();assert.equal(f.requests[0].body.rows.length,0);});
test('sheet configuration accepts only Google Sheets URLs and named tabs',()=>{assert.equal(sheetSettings({url:'https://docs.google.com/spreadsheets/d/'+id+'/edit',tab_name:'Leads'}).spreadsheet_id,id);assert.throws(()=>sheetSettings({url:'https://evil.example/'+id,tab_name:'Leads'}));assert.throws(()=>sheetSettings({spreadsheet_id:id}));assert.ok(source.includes('@OnlyCurrentDoc'));});
test('review setup appends columns without rewriting the lead and keeps the existing key on upgrade',()=>{
 const f=fixture();f.ctx.installInboundDesk();assert.equal(f.grid()[1][0],'Practice Person');assert.ok(f.grid()[0].includes('Would send'));assert.ok(f.grid()[0].includes('Inbound Draft ID'));
 const before=f.grid()[0].length;f.ctx.installInboundDesk();assert.equal(f.grid()[0].length,before);
 const upgraded=appsScript({...settings,token:''},readFileSync(new URL('../static/import-data.js',import.meta.url),'utf8'));const next={...f.ctx};vm.createContext(next);vm.runInContext(upgraded,next);next.installInboundDesk();assert.equal(JSON.parse(f.props.INBOUND_DESK_CONFIG).token,settings.token);
});
